name: dio_cache_ttl
description: A Dio-based caching solution with Time-to-Live (TTL) support, enabling efficient storage and retrieval of HTTP responses using the file system. Ideal for optimizing network performance and reducing redundant requests.
version: 0.3.3 # Increment version (e.g., minor update)
homepage: https://github.com/cas8398/dio_cache_ttl
repository: https://github.com/cas8398/dio_cache_ttl
issue_tracker: https://github.com/cas8398/dio_cache_ttl/issues
documentation: https://github.com/cas8398/dio_cache_ttl

environment:
  sdk: ">3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15
  http_mock_adapter: ^0.6.1
  mocktail: ^1.0.4

topics:
  - cache
  - ttl
  - dio
  - file

# The following section is specific to Flutter packages.
flutter:
  generate: true
